# Generated by Django 3.2 on 2022-08-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Not bad'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
